# Generated by Django 2.0.2 on 2018-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
